"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "zh" | "en";
export const DEFAULT_LANGUAGE: Language = "zh";
type Dictionary = Record<string, string>;

const messages: Record<Language, Dictionary> = {
  zh: {
    "nav.home": "首页", "nav.forYou": "为你推荐", "nav.myMusic": "我的音乐", "nav.discover": "探索", "nav.timeline": "时间线", "nav.lab": "实验室", "nav.primary": "主导航",
    "status.loading": "正在加载…",
    "home.heroKicker": "从你的音乐开始", "home.libraryOverview": "你的音乐库", "home.libraryEmpty": "还没有音乐库。先导入一个歌单，MusicScope 会从这里开始理解你的偏好。", "home.concerts": "相关演出", "home.labCta": "在实验室试听人声与伴奏",
    "playlist.step1": "粘贴歌单链接", "playlist.step2": "获取歌曲列表", "playlist.step3": "粘贴并导入", "playlist.otherMethods": "其他导入方式", "playlist.membershipNote": "歌单导入代表收藏/音乐库归属，不会被记录为播放历史。MusicScope 不抓取或逆向解析 NetEase。",
    "lab.eyebrow": "MusicScope Lab", "lab.title": "人声 / 伴奏分离实验", "lab.description": "上传本地音频，生成两条同步音轨，并独立调整人声与伴奏的音量。",
    "profile.recentEmpty": "暂无近期收听数据。收藏歌单会帮助建立长期偏好；导入带时间信息的收听记录后，这里会显示近期变化。", "profile.libraryTracks": "首收藏曲目", "profile.topArtists": "常听艺术家", "profile.searchLibrary": "搜索你的音乐库", "profile.libraryEmpty": "你的音乐库还是空的。先导入一个歌单吧。", "profile.dataManagement": "数据管理", "profile.dataManagementHint": "导入记录与修正工具", "profile.showingFirst": "当前显示前 {count} 首",
    "timeline.emptyHistory": "收藏歌单可以用于长期偏好和推荐，但没有时间信息时，MusicScope 不会虚构你的音乐时间线。", "timeline.importHint": "如果你有带时间信息的收听记录，可以导入 CSV。",
    "timeline.evidenceNewArtists": "新增艺术家 {count} 位", "timeline.evidenceCompletion": "平均完成度 {delta}%", "timeline.evidenceSkip": "跳过率 {delta}%", "timeline.evidenceFrequency": "聆听次数从 {previous} 变为 {current}",
    "recommendation.familiar": "熟悉", "recommendation.adventurous": "大胆探索", "recommendation.noCandidates": "还没有足够的音乐库内容生成推荐。先导入一些音乐，或导入收听记录。", "recommendation.libraryBasis": "基于你的音乐库与聆听行为",
    "evidence.long_term_genre": "匹配你长期偏好的 {value}", "evidence.artist_affinity": "来自你音乐库中熟悉的艺术家", "evidence.short_term_state": "符合你最近的聆听状态", "evidence.relationship": "来自你经常重播或完整听完的关联", "evidence.novelty": "来自尚未熟悉或较少听过的艺术家", "evidence.exploration": "因为探索度较高而选出的跨界尝试", "evidence.feedback_penalty": "根据近期负面反馈降低排序", "evidence.balanced_match": "平衡了偏好匹配、新鲜感与多样性",
    "header.eyebrow": "音乐智能工作台", "header.intro": "导入聆听记录，理解你的音乐，并发现下一首。", "header.ready": "可以导入 CSV 文件。", "home.title": "你的音乐，值得被理解。", "home.subtitle": "从一个播放列表开始，MusicScope 会整理你的聆听轨迹、偏好和发现。", "home.profile": "音乐画像摘要", "home.forYou": "为你推荐预览", "home.audio": "双音轨音频分离", "home.audioDescription": "上传一首歌，分离人声与伴奏并同步播放。", "home.open": "打开", "home.importTitle": "导入你的音乐", "home.importDescription": "粘贴播放列表链接，或使用 CSV 作为可靠备选。", "playlist.placeholder": "粘贴 NetEase Cloud Music 播放列表链接", "playlist.detect": "检测链接", "playlist.import": "导入并分析", "playlist.csv": "或导入 CSV", "playlist.detected": "已识别：{provider} · 播放列表 {id}", "playlist.unsupported": "当前无法可靠读取此播放列表的完整曲目，请使用 CSV 导入。", "playlist.invalid": "请粘贴有效的播放列表链接。", "playlist.checking": "正在检查播放列表…", "playlist.csvReady": "可以导入 CSV 文件。",
    "import.button": "导入 CSV", "import.batches": "导入记录", "import.summary": "共 {total} 次导入 · {withRecords} 次有记录 · {empty} 次为空", "import.showAll": "显示全部", "import.showLess": "收起", "import.noImports": "还没有导入记录。", "import.records": "{count} 条记录", "import.empty": "空导入", "import.resolved": "已匹配", "import.ambiguous": "有歧义", "import.unresolved": "未匹配",
    "review.title": "待处理", "review.none": "没有待处理的记录。", "review.assign": "分配曲目…", "review.exclude": "排除", "review.resolved": "已匹配记录", "review.resolvedEmpty": "匹配后的记录会显示在这里。", "review.canonical": "标准曲目",
    "timeline.title": "音乐时间线", "timeline.description": "系统观察只展示可测量的聆听变化，个人意义留在音乐记忆中。", "timeline.recalculate": "重新计算证据", "timeline.empty": "生成第一条基于证据的时间线。", "timeline.score": "变化分数 {score}", "timeline.memories": "用户记忆", "timeline.addMemory": "添加记忆", "timeline.editMemory": "编辑记忆", "timeline.delete": "删除", "timeline.memoryPrompt": "为这一时期添加个人记忆", "timeline.memoryEditPrompt": "编辑记忆", "timeline.updated": "时间线已根据有效聆听数据更新。", "timeline.recalculating": "正在重新计算时间线证据…",
    "recommendation.title": "为你推荐 / 探索", "recommendation.description": "滑块会调整熟悉匹配与有依据探索之间的平衡。", "recommendation.exploration": "探索度", "recommendation.why": "为什么推荐？", "feedback.like": "喜欢", "feedback.skip": "跳过", "feedback.dislike": "不喜欢", "feedback.skipReason": "跳过原因", "feedback.notToday": "今天不想听", "feedback.tooLoud": "太吵", "feedback.tooSlow": "太慢", "feedback.dislikeVocals": "不喜欢人声", "feedback.simplyDislike": "就是不喜欢", "recommendation.unavailable": "推荐暂时不可用，请确认 API 已启动。",
    "profile.title": "音乐画像", "profile.description": "长期偏好与最近 {days} 天的聆听状态对比。", "profile.longTerm": "长期偏好", "profile.recent": "近期状态", "profile.noData": "还没有聆听数据。", "profile.tracks": "{count} 首曲目", "profile.completion": "完成度 {percent}%", "profile.replays": "{count} 次重播", "profile.genres": "流派", "profile.artists": "艺术家", "profile.none": "暂无",
    "audio.eyebrow": "音频分离", "audio.title": "分离并聆听", "audio.description": "离线分离会生成两条同步音轨，可实时调整各层音量而无需重新运行模型。", "audio.choose": "选择音频", "audio.formats": "WAV、MP3、M4A/AAC 或 FLAC · 最长 15 分钟", "audio.separate": "分离", "audio.retry": "重试", "audio.vocals": "人声", "audio.instrumental": "伴奏", "audio.play": "播放", "audio.pause": "暂停", "audio.seek": "定位", "audio.loaded": "两条音轨已加载", "audio.ready": "分离已完成，可以播放", "audio.chooseMessage": "选择短音频文件以创建同步音轨。", "audio.uploading": "正在上传并验证音频…", "audio.complete": "分离完成。加载两条音轨即可一起播放。", "audio.normalized": "音频已标准化，正在开始分离…", "audio.cached": "缓存的分离结果已准备好。", "audio.processing": "正在分离人声和伴奏…", "audio.queued": "分离已排队…", "audio.failed": "分离失败，请重试。", "audio.unavailable": "音频服务不可用，请确认 API 和 FFmpeg 已启动。", "audio.loading": "正在加载两条音轨…", "audio.playing": "正在播放同步音轨。", "audio.loadError": "两条音轨都加载后才能播放，请重试。",
    "concert.eyebrow": "探索 · 现场演出", "concert.title": "即将举行的演出", "concert.description": "为与你聆听相关的艺术家进行轻量演出查询。", "concert.loading": "正在查询演出日期…", "concert.error": "演出服务暂不可用，请稍后重试。", "concert.providerUnavailable": "暂时无法获取该艺人的实时演出信息。", "concert.stale": "部分演出信息来自较早的缓存查询。", "concert.none": "相关艺术家暂无即将举行的演出。", "concert.demo": "确定性演示数据 · 非实时演出", "concert.details": "查看详情 ↗", "concert.venueUnavailable": "场地信息不可用", "concert.search": "搜索艺术家", "concert.searchPlaceholder": "输入艺术家名称", "concert.searchButton": "搜索", "concert.searching": "正在搜索…", "concert.defaultArtist": "milet",
    "status.imported": "已导入 {count} 条记录。", "status.api": "API 尚未连接。", "status.timeline": "时间线已更新。", "status.error": "操作失败，请重试。", "status.completed": "已完成", "status.pending": "等待中", "status.processing": "处理中", "status.failed": "失败", "status.resolved": "已匹配", "status.ambiguous": "有歧义", "status.unresolved": "未匹配", "status.manually_corrected": "已手动修正", "status.excluded": "已排除",
    "playlist.textTab": "歌单文本导入", "playlist.textHelp": "1. 复制 NetEase 歌单链接。 2. 打开转换工具并粘贴链接。 3. 点击获取歌单，再点击复制结果。 4. 将曲目文本粘贴回这里。", "playlist.openTool": "打开歌单转换工具 ↗", "playlist.textPlaceholder": "Track Name - Artist\nTrack Name — Artist", "playlist.parse": "解析歌单", "playlist.summary": "共 {total} 行 · 有效曲目 {valid} · 待处理 {invalid} · 艺术家 {artists}", "playlist.stageParse": "解析歌单", "playlist.stageResolve": "识别歌曲", "playlist.stageProfile": "更新音乐画像", "playlist.stageDone": "完成", "playlist.complete": "已导入 {count} 首曲目 · 已匹配 {resolved} · 未匹配 {unresolved} · 艺术家 {artists}", "playlist.viewMusic": "查看我的音乐", "playlist.attribution": "歌单转换由第三方开源工具 GoMusic 提供辅助。MusicScope 不需要你的 NetEase 密码；若工具不可用，可以使用 CSV。", "timeline.demo": "确定性演示数据 · 合成聆听历史", "role.PRECISE_MATCH": "精准匹配", "role.ADJACENT_EXPLORATION": "相邻探索", "role.CROSS_BOUNDARY_DISCOVERY": "跨界发现", "role.BOLD_TRY": "大胆尝试",
  },
  en: {
    "nav.home": "Home", "nav.forYou": "For You", "nav.myMusic": "My Music", "nav.discover": "Discover", "nav.timeline": "Timeline", "nav.lab": "Lab", "nav.primary": "Primary navigation",
    "status.loading": "Loading…",
    "home.heroKicker": "Start with your music", "home.libraryOverview": "Your music library", "home.libraryEmpty": "Your library is empty. Import a playlist and MusicScope will start learning your preferences from there.", "home.concerts": "Related concerts", "home.labCta": "Try vocals and instrumental in the Lab",
    "playlist.step1": "Paste the playlist link", "playlist.step2": "Get the song list", "playlist.step3": "Paste and import", "playlist.otherMethods": "Other import methods", "playlist.membershipNote": "A playlist import adds saved library membership; it is not listening history. MusicScope does not scrape or reverse-engineer NetEase.",
    "lab.eyebrow": "MusicScope Lab", "lab.title": "Vocal / instrumental separation", "lab.description": "Upload local audio, create two synchronized stems, and adjust vocal and instrumental volume independently.",
    "profile.recentEmpty": "No recent listening data yet. A saved playlist helps build long-term taste; timestamped listening history will make recent changes visible here.", "profile.libraryTracks": "saved tracks", "profile.topArtists": "Top artists", "profile.searchLibrary": "Search your library", "profile.libraryEmpty": "Your music library is empty. Start by importing a playlist.", "profile.dataManagement": "Data management", "profile.dataManagementHint": "Import history and correction tools", "profile.showingFirst": "Showing the first {count}",
    "timeline.emptyHistory": "Saved playlists can support long-term preferences and recommendations, but without timestamps MusicScope will not invent a music timeline.", "timeline.importHint": "If you have timestamped listening history, you can import it as CSV.",
    "timeline.evidenceNewArtists": "{count} new artists", "timeline.evidenceCompletion": "Average completion {delta}%", "timeline.evidenceSkip": "Skip rate {delta}%", "timeline.evidenceFrequency": "Listening events changed from {previous} to {current}",
    "recommendation.familiar": "Familiar", "recommendation.adventurous": "Adventurous", "recommendation.noCandidates": "There is not enough library data for recommendations yet. Import music or listening history first.", "recommendation.libraryBasis": "Based on your music library and listening behavior",
    "evidence.long_term_genre": "matches your long-term {value} preference", "evidence.artist_affinity": "comes from a familiar artist in your library", "evidence.short_term_state": "matches your recent listening state", "evidence.relationship": "builds on a frequently replayed or completed relationship", "evidence.novelty": "comes from an unfamiliar or lightly played artist", "evidence.exploration": "selected as a cross-boundary option because exploration is high", "evidence.feedback_penalty": "down-ranked by recent negative feedback", "evidence.balanced_match": "balances profile fit, freshness, and diversity",
    "header.eyebrow": "Music intelligence workspace", "header.intro": "Import listening history, understand your music, and discover what comes next.", "header.ready": "Ready for a CSV import.", "home.title": "Your music deserves to be understood.", "home.subtitle": "Start with a playlist. MusicScope organizes your listening history, preferences, and discoveries.", "home.profile": "Music profile summary", "home.forYou": "For You preview", "home.audio": "Two-stem audio separation", "home.audioDescription": "Upload a track, separate vocals and instrumental, and play them in sync.", "home.open": "Open", "home.importTitle": "Import your music", "home.importDescription": "Paste a playlist link, or use CSV as the reliable fallback.", "playlist.placeholder": "Paste a NetEase Cloud Music playlist link", "playlist.detect": "Detect link", "playlist.import": "Import and analyze", "playlist.csv": "Or import CSV", "playlist.detected": "Detected: {provider} · Playlist {id}", "playlist.unsupported": "The complete track list cannot currently be read reliably. Use CSV import instead.", "playlist.invalid": "Paste a valid playlist link.", "playlist.checking": "Checking playlist…", "playlist.csvReady": "Ready for a CSV import.",
    "import.button": "Import CSV", "import.batches": "Import batches", "import.summary": "{total} imports · {withRecords} with records · {empty} empty", "import.showAll": "Show all", "import.showLess": "Show less", "import.noImports": "No imports yet.", "import.records": "{count} records", "import.empty": "Empty import", "import.resolved": "resolved", "import.ambiguous": "ambiguous", "import.unresolved": "unresolved",
    "review.title": "Needs review", "review.none": "No unresolved records.", "review.assign": "Assign track…", "review.exclude": "Exclude", "review.resolved": "Resolved records", "review.resolvedEmpty": "Resolved records will appear here.", "review.canonical": "Canonical track",
    "timeline.title": "Timeline", "timeline.description": "System observations show measurable listening changes. Personal meaning stays in memories.", "timeline.recalculate": "Recalculate evidence", "timeline.empty": "Generate the first evidence-based timeline.", "timeline.score": "Change score {score}", "timeline.memories": "User memories", "timeline.addMemory": "Add memory", "timeline.editMemory": "Edit memory", "timeline.delete": "Delete", "timeline.memoryPrompt": "Add a personal memory for this period", "timeline.memoryEditPrompt": "Edit memory", "timeline.updated": "Timeline updated from effective listening data.", "timeline.recalculating": "Recalculating timeline evidence…",
    "recommendation.title": "For You / Discover", "recommendation.description": "The slider changes the balance between familiar matches and measured discovery.", "recommendation.exploration": "Exploration", "recommendation.why": "Why this?", "feedback.like": "Like", "feedback.skip": "Skip", "feedback.dislike": "Dislike", "feedback.skipReason": "Skip reason", "feedback.notToday": "Not for today", "feedback.tooLoud": "Too loud", "feedback.tooSlow": "Too slow", "feedback.dislikeVocals": "Dislike vocals", "feedback.simplyDislike": "Simply dislike", "recommendation.unavailable": "Recommendations are unavailable until the API is ready.",
    "profile.title": "Music profile", "profile.description": "Long-term taste compared with the most recent {days} days of listening.", "profile.longTerm": "Long-term", "profile.recent": "Recent state", "profile.noData": "No listening data yet.", "profile.tracks": "{count} tracks", "profile.completion": "{percent}% completion", "profile.replays": "{count} replays", "profile.genres": "Genres", "profile.artists": "Artists", "profile.none": "None yet",
    "audio.eyebrow": "Audio separation", "audio.title": "Separate and listen", "audio.description": "Offline separation creates two synchronized stems. Adjust either layer live without rerunning the model.", "audio.choose": "Choose audio", "audio.formats": "WAV, MP3, M4A/AAC, or FLAC · max 15 minutes", "audio.separate": "Separate", "audio.retry": "Retry", "audio.vocals": "Vocals", "audio.instrumental": "Instrumental", "audio.play": "Play", "audio.pause": "Pause", "audio.seek": "Seek", "audio.loaded": "Both stems loaded", "audio.ready": "Separation ready", "audio.chooseMessage": "Choose a short audio file to create synchronized stems.", "audio.uploading": "Uploading and validating audio…", "audio.complete": "Separation complete. Load both stems to play them together.", "audio.normalized": "Audio normalized. Starting separation…", "audio.cached": "Cached separation is ready.", "audio.processing": "Separating vocals and instrumental…", "audio.queued": "Separation queued…", "audio.failed": "Separation failed. Try again.", "audio.unavailable": "Audio service is unavailable. Check that the API and FFmpeg are running.", "audio.loading": "Loading both stems…", "audio.playing": "Playing synchronized stems.", "audio.loadError": "Both stems must load before playback can start. Try again.",
    "concert.eyebrow": "Discover · live dates", "concert.title": "Upcoming concerts", "concert.description": "A lightweight lookup for artists already relevant to your listening.", "concert.loading": "Checking upcoming dates…", "concert.error": "Concert provider unavailable. Try again later.", "concert.providerUnavailable": "Live concert information is temporarily unavailable.", "concert.stale": "Some concert information is from a previous cached lookup.", "concert.none": "No upcoming concerts found for your relevant artists.", "concert.demo": "Deterministic demo fixture · not a live listing", "concert.details": "View details ↗", "concert.venueUnavailable": "Venue information unavailable", "concert.search": "Search artist", "concert.searchPlaceholder": "Enter an artist name", "concert.searchButton": "Search", "concert.searching": "Searching…", "concert.defaultArtist": "milet",
    "status.imported": "Imported {count} records.", "status.api": "API is not reachable yet.", "status.timeline": "Timeline updated from effective listening data.", "status.error": "The operation failed. Try again.", "status.completed": "completed", "status.pending": "pending", "status.processing": "processing", "status.failed": "failed", "status.resolved": "resolved", "status.ambiguous": "ambiguous", "status.unresolved": "unresolved", "status.manually_corrected": "manually corrected", "status.excluded": "excluded",
    "playlist.textTab": "Playlist text import", "playlist.textHelp": "1. Copy your NetEase playlist link. 2. Open the converter and paste the link. 3. Click fetch, then copy the result. 4. Paste the track text here.", "playlist.openTool": "Open playlist converter ↗", "playlist.textPlaceholder": "Track Name - Artist\nTrack Name — Artist", "playlist.parse": "Parse playlist", "playlist.summary": "{total} lines · {valid} valid tracks · {invalid} for review · {artists} artists", "playlist.stageParse": "Parse playlist", "playlist.stageResolve": "Resolve tracks", "playlist.stageProfile": "Update profile", "playlist.stageDone": "Complete", "playlist.complete": "Imported {count} tracks · {resolved} resolved · {unresolved} unresolved · {artists} artists", "playlist.viewMusic": "View My Music", "playlist.attribution": "Playlist conversion is assisted by the third-party open-source GoMusic tool. MusicScope does not require your NetEase password; CSV remains available if the tool is unavailable.", "timeline.demo": "Deterministic demo data · synthetic listening history", "role.PRECISE_MATCH": "Precise Match", "role.ADJACENT_EXPLORATION": "Adjacent Exploration", "role.CROSS_BOUNDARY_DISCOVERY": "Cross-boundary Discovery", "role.BOLD_TRY": "Bold Try",
  },
};

export function translate(language: Language, key: string, values?: Record<string, string | number>): string {
  let result = messages[language][key] ?? messages.en[key] ?? key;
  Object.entries(values ?? {}).forEach(([name, value]) => { result = result.replace(`{${name}}`, String(value)); });
  return result;
}

type I18nValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string, values?: Record<string, string | number>) => string };
const I18nContext = createContext<I18nValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(DEFAULT_LANGUAGE);
  useEffect(() => {
    const saved = window.localStorage.getItem("musicscope-language");
    if (saved === "zh" || saved === "en") setLanguage(saved);
  }, []);
  useEffect(() => { document.documentElement.lang = language === "zh" ? "zh-CN" : "en"; }, [language]);
  const changeLanguage = (next: Language) => { setLanguage(next); window.localStorage.setItem("musicscope-language", next); };
  const value = useMemo(() => ({ language, setLanguage: changeLanguage, t: (key: string, values?: Record<string, string | number>) => translate(language, key, values) }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n(): I18nValue {
  const value = useContext(I18nContext);
  if (!value) throw new Error("useI18n must be used inside LanguageProvider");
  return value;
}
